import './bootstrap';
// import 'laravel-datatables-vite';

import 'jszip';
import 'pdfmake';
import DataTable from 'datatables.net-bs4';
import AutofillBs4 from'datatables.net-autofill-bs4';
import ButtonsBs4 from 'datatables.net-buttons-bs4';
import Buttons from 'datatables.net-buttons';
import ButtonsDt from 'datatables.net-buttons-dt';
import Colvis from 'datatables.net-buttons/js/buttons.colVis.js';
import Buttonshtml5 from 'datatables.net-buttons/js/buttons.html5.js';
import ButtonsPrint from 'datatables.net-buttons/js/buttons.print.js';
import ColreorderBs4 from 'datatables.net-colreorder-bs4';
import Datetime from 'datatables.net-datetime';
import Fixedcolumns from 'datatables.net-fixedcolumns-bs4';
import Fixedheader from 'datatables.net-fixedheader-bs4';
import KeytableBs4 from 'datatables.net-keytable-bs4';
import ResponsiveBs4 from 'datatables.net-responsive-bs4';
import RowgroupBs4 from 'datatables.net-rowgroup-bs4';
import RowreorderBs4 from 'datatables.net-rowreorder-bs4';
import Scroller from 'datatables.net-scroller-bs4';
import Searchbuilder from 'datatables.net-searchbuilder-bs4';
import Staterestore from 'datatables.net-searchpanes-bs4';
import Select from 'datatables.net-select-bs4';
DataTable.use(Select);
DataTable.use(AutofillBs4);
DataTable.use(ButtonsBs4);
DataTable.use(Buttons);
DataTable.use(ButtonsDt);
// DataTable.use(Colvis);
// DataTable.use(Buttonshtml5);
// DataTable.use(ButtonsPrint);
DataTable.use(ColreorderBs4);
DataTable.use(Datetime);
DataTable.use(Fixedcolumns);
DataTable.use(Fixedheader);
DataTable.use(KeytableBs4);
DataTable.use(ResponsiveBs4);
DataTable.use(RowgroupBs4);
DataTable.use(RowreorderBs4);
DataTable.use(Staterestore);
DataTable.use(Searchbuilder);
DataTable.use(Scroller);
Colvis();
Buttonshtml5();
ButtonsPrint();
window.DataTable = DataTable;